### ISSUE TITLE
LoadANNIEEvent tool is slow

### ISSUE THREAD

**Issue by sjgardiner** [ANNIEsoft/ToolAnalysis#43]
When I attempt to use the LoadANNIEEvent tool with BoostStore output files from the Phase I analysis (e.g., `/pnfs/annie/scratch/anniepro/toolanalysis/0653/RAWDataR653S9p2_reco` on anniegpvm01), it takes a long time to read each event from disk. I can currently reprocess the raw file faster than I can loop through all of the processed events.

**Comment by brichards64** [comment]
You may be reading events in a non optimal way?

Also are you reading the events sequentially or jumping back and forward though the event record?

**Comment by brichards64** [comment]
So there is definitely a memory leak in your Tool. When monitoring its output its notably taking longer each event it loads. So i just wrote a very simple load tool to load every event in the same file and time stamped mine vs yours.

Mine time to read all 383 events (with ToolDAQ overheads): 

real    1m4.785s
user    0m58.626s
sys     0m4.736s

Yours to read only 50 events (sorry but i got bored waiting so didnt do the full set) :

real    3m31.141s
user    3m17.974s
sys     0m12.732s

So ill delve into your code and find out why.

**Comment by brichards64** [comment]
Found it. Very simple error you had made.

Basically you forgot to set the new file bool flag to false after loading a new file. So every event it thought was a new file and so reloaded the file from scratch for every single event. Iv fixed this and the new time of your tool to load all 383 events is:

real    1m0.758s
user    0m55.858s
sys     0m3.508s

Whilst fixing that bug and testing i noticed another bug in your code with the end of file list logic. You had forgotten to increment the file list entry prior to the logical test that it had reached the end of the list. This caused a seg fault as it tired to load a non existent file after finishing all the files in the list. So iv fixed this as well.
